#!/bin/bash

if ! [ -e "$HOME/.alsoftrc" ]; then
  echo "period_size = 32" > "$HOME/.alsoftrc"
  echo "periods = 4" >> "$HOME/.alsoftrc"
  echo "allow-moves = true" >> "$HOME/.alsoftrc"
fi

export BUCKLESPRING_WAV_DIR=$SNAP/wav

if [ "$SNAP_ARCH" = "amd64" ]; then
  if grep -qs libfluidsynth.so.1 $SNAP/usr/lib/x86_64-linux-gnu/libalure.so.1; then
    export LD_LIBRARY_PATH=$SNAP/extra-libs:$LD_LIBRARY_PATH
  fi
fi

exec "$@"
