name: bucklespring
license: GPL-2.0
adopt-info: buckle
summary: Nostalgia bucklespring keyboard sound
description: |
  This project emulates the sound of my old faithful IBM Model-M space saver
  bucklespring keyboard while typing on my notebook, mainly for the purpose of
  annoying the hell out of my coworkers.

  Bucklespring runs as a background
  process and plays back the sound of each key pressed and released on your
  keyboard, just as if you were using an IBM Model-M. The sound of each key has
  carefully been sampled, and is played back while simulating the proper
  distance and direction for a realistic 3D sound palette of pure nostalgic
  bliss.

base: core20
grade: stable
confinement: strict

apps:
  buckle:
    environment:
      ALWAYS_USE_PULSEAUDIO: '1'
    command-chain:
      - snap/command-chain/alsa-launch
      - buckle-snap.run
    command: buckle
    plugs: [x11, audio-playback, alsa]

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  deps:
    plugin: nil
    stage-packages:
      - libalure1
      - libdumb1
      - libflac8
      - libfluidsynth2
      - libmodplug1
      - libmpg123-0
      - libopenal1
      - libsndfile1
      - libsndio7.0
      - libvorbisfile3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxtst6

  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

  buckle:
    plugin: make
    source: https://github.com/zevv/bucklespring.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags --exclude="*win32*")"
    override-build: |
      make
      cp -v $SNAPCRAFT_PART_BUILD/buckle $SNAPCRAFT_PART_INSTALL
      cp -va $SNAPCRAFT_PART_BUILD/wav $SNAPCRAFT_PART_INSTALL
    build-packages:
      - pkg-config
      - libopenal-dev
      - libalure-dev
      - libxtst-dev
    after:
      - alsa-mixin

  launcher:
    plugin: dump
    source: .
    filesets:
      launcherset:
        - buckle-snap.run
        - extra-libs
    stage: [ $launcherset ]
    prime: [ $launcherset ]
